services:
  app_storefront:
    container_name: app_storefront
    image: app_storefront
    env_file:
      - storefront/.env
    build:
      context: .
      dockerfile: Dockerfile-storefront
    volumes:
      - ./storefront:/usr/storefront
    ports:
      - "8000:8000"
    depends_on:
      - app_db
      - app_storeback
  
  app_storeback:
    container_name: app_storeback
    image: app_storeback
    env_file:
      - backend/.env
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./storefront:/usr/storefront
    ports:
      - "7001:7001"
      - "9000:9000"
    depends_on:
      - app_db

  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:16
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app_redis:
    image: redis:7.2-alpine
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - 6379:6379

volumes:
  app_pg_data:
    driver: "local"